import Verbose.French.Assume
import Verbose.French.By
import Verbose.French.Since
import Verbose.French.Claim
import Verbose.French.Fix
import Verbose.French.Lets
import Verbose.French.Set
import Verbose.French.We
import Verbose.French.Calc
